### PR TITLE
[Depends on #18] Refactored CLI argument parsing logic, added package actions

### PR DESCRIPTION
**Pull request by dshynkev**
Looking at the implementation of CLI actions, one can notice that parsing is currently done suboptimally:
- instead of relying on the built-in functionality provided by `argparse`, we are filtering flags manually
- invalid actions are not rejected (e.g. `wcosa asdf` falls through silently)
- there is no way to implement two-level commands (e.g. `wcosa package install`)

I propose an alternative implementation with a hierarchical structure:
- `wcosa` requires an `action`. Actions are documented under `wcosa -h`.
  - `wcosa action` takes flags depending on the type of `action`, e.g. `create` requires `--board` and optionally takes `--ide`. All actions take `--path`. Each action's flags are documented under `wcosa action -h`.
  - `wcosa package` is an action that requires a `command`, one of `install`, `update`, `remove`. This is documented under `wcosa package -h`.
    - `wcosa package install` and `wcosa package remove` take a list of `package`s, arbitrarily long.

### CODE REVIEW

**Comment by dshynkev** [comment]
CI will fail as long as `package_manager` is not merged, but I'm just leaving this here for now.

**Comment by Mogball** [comment]
Merged #18, can you add some tests for the new package functionality? We're basically just running a script under TOX lol `test.sh`

**Comment by dhillondeep** [comment]
I was gonna do that good job doing it already. It relates to the issue #24 as well

**Comment by dshynkev** [comment]
Added a test case as needed and a missing parser that testing discovered.

Also, a regression (compared to git submodules) surfaced in `package_manager`: since it assumed the main branch on remote repos to be called `master`, it would fail to fetch, say, `waterloop/wlib` (but not `waterloop/waterloop-wlib`!), which has no `master` branch, unless the `library` branch was explicitly specified. This is now fixed in be5ec2dbfbee356ac1c5a389d3fbc327823da106 (first of the three new commits).

**Review by Mogball — APPROVED** [review]
lgtm nice work

**Pull request merged**
